### ISSUE TITLE
Is the repo still maintained?

### ISSUE THREAD

**Issue by roaldarbol** [paolobrasolin/ctan-submit-action#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Original goal

Hey there! I was looking for exactly this, a CTAN Github action, and it seems promising. However, your links to examples no longer work, and the documentation falls a bit short, so I'm a bit unsure about how to proceed. (Full disclosure, I don't have vast experience with GH Actions).

Can this plugin be used to upload to CTAN every time a new version is released on Github? And how would that look? Thanks!

**Comment by paolobrasolin** [comment]
Yes, this is still maintained @roaldarbol! I simply haven't touched this in a while because it's feature complete.

Thanks for letting me know the links in the readme rotted away! I just freshened them up. You should now be able to follow them to see the action at work.

> Can this plugin be used to upload to CTAN every time a new version is released on Github? And how would that look?

Yes it can! Here are some real-life examples:

* here is a fresh example from a very popular project: https://github.com/latex-lsp/texlab/blob/3cbbe6feae23971892219eb11925994bf70526b9/.github/workflows/publish.yml#L140-L149
* here is another example from a project of mine: https://github.com/paolobrasolin/commutative-diagrams/blob/19a6deb9d9d25eea446ad095518d236b8383e142/.github/workflows/release.yml#L83-L94
* and here is the full list of projects using this action for further inspiration: https://github.com/paolobrasolin/ctan-submit-action/network/dependents -- hopefully this will include yours soon 😀 

As you can see the usage of this action is pretty much always the same snippet, and the bulk of the complexity around it.

> the documentation falls a bit short, so I'm a bit unsure about how to proceed. (Full disclosure, I don't have vast experience with GH Actions).

All options are documented, so please let me know if seeing live examples is enough to get you going!
I wouldn't like to put off anyone, regardless of experience level. ❤️ 

I'll leave this issue open for now, in case you find something unclear that I can improve.

**Comment by roaldarbol** [comment]
Thanks, good to hear! And I really appreciate your effort to assist. 

I think your own example looks the simplest, so maybe I can ask about that. I guess I'd need to include most of the other actions in there for things to work properly, is that right? Maybe you could make an annotated example of it in the wiki or elsewhere (here?) of the minimal sequence of actions needed, and where one would need to edit things?

The reason it might be useful is, well , at least for me, wanting to upload to CTAN automatically brought me here - so it might be really helpful for others after me to see a full minimal example workflow to make it easy to implement. :-)

**Comment by paolobrasolin** [comment]
@roaldarbol good idea, I added a couple of fleshed-out examples to the readme!

**Comment by roaldarbol** [comment]
Thanks, that helps a lot! In your example, do you build the `.zip` yourself, or is this also carried out by an action?

**Comment by paolobrasolin** [comment]
I implemented the build details in a `Makefile` I call from this step: https://github.com/paolobrasolin/commutative-diagrams/blob/19a6deb9d9d25eea446ad095518d236b8383e142/.github/workflows/release.yml#L39-L42

You can see it here https://github.com/paolobrasolin/commutative-diagrams/blob/main/Makefile but there's a lot of very project-specific logic, so you can probably get away with something simpler, @roaldarbol.

**Comment by roaldarbol** [comment]
Just checking: Is the reason you do the build process to test that it works? Or does your project have many components? My project is a single `.cls` file, so I figured I can just zip up the repo without a more elaborate "building" process?

**Comment by paolobrasolin** [comment]
It's because there's a lot of components to the projects, and they need to be recombined/interpolated. Tests are actually run in a separate workflow.

If it's a simple CLS you can definitely get away with "zip it and call it a day".
In any case, requirements are straightforward and well documented on CTAN:
* https://ctan.org/help/upload-pkg
* https://ctan.org/file/help/ctan/CTAN-upload-addendum

**Comment by roaldarbol** [comment]
Cool thanks! I'll do that then. 👍
